<?php

function surprise_tutorial_menu(){
    $items['surprise_tutorial'] = array(
        'title' => 'Surprise Me!',
        'page callback' => 'random_tutorial',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function random_tutorial(){

    //db query
    //from node select all with type tutorial
    $results = db_select('node', 'n')
        -> fields('n')
        -> condition('type', 'tutorial')
        -> execute()
        -> fetchAllAssoc('title');
//

//    print_r($results);
    foreach($results as $value){
        $tutorial_name = ($value->title);
        //convert white spaces to -
        $tutorial_url_name = preg_replace("/\s/", "-", $tutorial_name);
        $tutorials[] = $tutorial_url_name;
    }

    print_r($tutorials);
    //picks random index from array
    $random_pick = array_rand($tutorials);
    $random_tutorial = $tutorials[$random_pick];

    $url = '/content/tutorial/' . $random_tutorial;

    drupal_goto($url);

}
