<?php

function simple_contact_form_alter(&$form, &$form_state, $form_id){
    if($form_id == 'contact_site_form'){
//        print '<pre>';
//        print_r($form);
//        print '</pre>';
        //change defaults
      $form['subject']['#default_value'] = 'Feedback';
      $form['copy']['#default_value'] = 1;
        //hide from user
      $form['subject']['#type'] = 'hidden';
      $form['copy']['#type'] = 'hidden';
    }
}